const GW = process.env.NEXT_PUBLIC_GATEWAY_URL || "http://2.24.127.197:30080";
const H = (t) => { const h={"Content-Type":"application/json"}; if(t) h["Authorization"]="Bearer "+t; return {headers:h}; };
const err = async (r,m) => { let msg=m; try{ const d=await r.json(); msg=d.mensagem||d.message||m; }catch{} throw new Error(msg); };
const get = (url,t) => fetch(GW+url,H(t)).then(r=>r.ok?r.json():err(r,"Erro na requisição."));
const post = (url,data,t) => fetch(GW+url,{method:"POST",...H(t),body:JSON.stringify(data)}).then(r=>r.ok?r.json():err(r,"Erro na requisição."));
const put = (url,data,t) => fetch(GW+url,{method:"PUT",...H(t),body:JSON.stringify(data)}).then(r=>r.ok?r.json():err(r,"Erro na requisição."));

export const loginUser = (d) => post("/auth/login",d,null);
export const registerUser = (d) => post("/usuario/cadastro",d,null);
export const fetchPacientes = (t) => get("/paciente",t);
export const createPatient = (d,t) => post("/paciente",d,t);
export const updatePatient = (id,d,t) => put("/paciente/"+id,d,t);
export const fetchPacienteById = (id,t) => get("/paciente/"+id,t);
export const fetchPacientesByNome = (nome,t) => get("/paciente/nome/"+encodeURIComponent(nome),t);
export const fetchPacienteByUsuario = (id,t) => get("/paciente/usuario/"+id,t);
export const fetchTriagens = (t) => get("/triagem",t);
export const classificarTriagem = (d,t) => post("/triagem/classificar",d,t);
export const fetchTriagemByPaciente = (id,t) => get("/triagem/paciente/"+id,t);
export const fetchProntuarios = (t) => get("/prontuario",t);
export const fetchProntuarioByPaciente = (id,t) => get("/prontuario/paciente/"+id,t);
export const createProntuario = (d,t) => post("/prontuario",d,t);
export const addConsulta = (id,d,t) => post("/prontuario/paciente/"+id+"/consulta",d,t);
export const addExame = (id,d,t) => post("/prontuario/paciente/"+id+"/exame",d,t);
export const addMedicamento = (id,d,t) => post("/prontuario/paciente/"+id+"/medicamento",d,t);
export const fetchNotificacoes = (t) => get("/notificacao",t);
export const fetchNotificacoesByPaciente = (id,t) => get("/notificacao/paciente/"+id,t);
